# PART 1

In [1]:
from bs4 import BeautifulSoup
import requests
import numpy as np
import pandas as pd

Scraping of the dataset from the wikipedia page

In [2]:
url = 'https://en.wikipedia.org/wiki/List_of_postal_codes_of_Canada:_M'
response = requests.get(url)
data = response.text
soup = BeautifulSoup(data, 'html.parser')
wiki_table = soup.find('table')
df = pd.read_html(str(wiki_table))[0]
df.head()

  Postal Code           Borough              Neighbourhood
0         M1A      Not assigned               Not assigned
1         M2A      Not assigned               Not assigned
2         M3A        North York                  Parkwoods
3         M4A        North York           Victoria Village
4         M5A  Downtown Toronto  Regent Park, Harbourfront

## Data preparation

Cleaning the data, whereby ignoring the 'Borough' contains 'Not assigned' cells

In [3]:
df2 = df[df['Borough'].str.contains('Not assigned') == False].reset_index()
df2.head(10)

,index,Postal Code,Borough,Neighbourhood
0,2,M3A,North York,Parkwoods
1,3,M4A,North York,Victoria Village
2,4,M5A,Downtown Toronto,"Regent Park, Harbourfront"
3,5,M6A,North York,"Lawrence Manor, Lawrence Heights"
4,6,M7A,Downtown Toronto,"Queen's Park, Ontario Provincial Government"
5,8,M9A,Etobicoke,"Islington Avenue, Humber Valley Village"
6,9,M1B,Scarborough,"Malvern, Rouge"
7,11,M3B,North York,Don Mills
8,12,M4B,East York,"Parkview Hill, Woodbine Gardens"
9,13,M5B,Downtown Toronto,"Garden District, Ryerson"

Combining the rows in which postal code and borough

In [4]:
df3 = df2.groupby(['Postal Code', 'Borough']) ['Neighbourhood'].apply(', '.join).reset_index()
df3.head(10)

  Postal Code      Borough                                    Neighbourhood
0         M1B  Scarborough                                   Malvern, Rouge
1         M1C  Scarborough           Rouge Hill, Port Union, Highland Creek
2         M1E  Scarborough                Guildwood, Morningside, West Hill
3         M1G  Scarborough                                           Woburn
4         M1H  Scarborough                                        Cedarbrae
5         M1J  Scarborough                              Scarborough Village
6         M1K  Scarborough      Kennedy Park, Ionview, East Birchmount Park
7         M1L  Scarborough                  Golden Mile, Clairlea, Oakridge
8         M1M  Scarborough  Cliffside, Cliffcrest, Scarborough Village West
9         M1N  Scarborough                      Birch Cliff, Cliffside West

In [5]:
df3.shape

(103, 3)

Save df3 as a csv file for later use

In [6]:
df3.to_csv('Capstone_1.csv')
print('Saved')

Saved